# Generated by Django 4.0.2 on 2023-09-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Balance', '0002_remove_rates_files_remove_rates_links_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchases',
            name='requisites',
        ),
        migrations.AlterField(
            model_name='purchases',
            name='date_time',
            field=models.DateTimeField(default='06.09.2023 17:47:19', verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Фамилия'),
        ),
    ]
