# Generated by Django 4.0.2 on 2023-09-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Balance', '0003_remove_purchases_requisites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='date_time',
            field=models.DateTimeField(default='06.09.2023 18:29:00', verbose_name='Время'),
        ),
    ]
